# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-08-16T09:47:45+00:00

from __future__ import annotations
from enum import StrEnum
from typing import Annotated, Any, Literal
from pydantic import BaseModel, Field, RootModel
from uuid import UUID
from datetime import date, datetime


class AccountType(StrEnum):
    stud = "stud"
    staff = "staff"


class Kind(RootModel[Literal["all_of"]]):
    root: Literal["all_of"] = Field(..., title="Kind")


class Kind2(RootModel[Literal["and"]]):
    root: Literal["and"] = Field(..., title="Kind")


class Kind4(RootModel[Literal["any_of"]]):
    root: Literal["any_of"] = Field(..., title="Kind")


class Type(RootModel[Literal["email"]]):
    root: Literal["email"] = Field("email", title="Type")


class EmailLogin(BaseModel):
    type: Literal["email"] = Field("email", title="Type")
    email: str = Field(..., title="Email")


class Operator(RootModel[Literal["equal"]]):
    root: Literal["equal"] = Field("equal", title="Operator")


class EqualPredicate(BaseModel):
    operator: Literal["equal"] = Field("equal", title="Operator")
    value: str = Field(..., title="Value")


class Kind6(RootModel[Literal["field"]]):
    root: Literal["field"] = Field(..., title="Kind")


class Kind8(RootModel[Literal["natural"]]):
    root: Literal["natural"] = Field("natural", title="Kind")


class Kind9(RootModel[Literal["organizational"]]):
    root: Literal["organizational"] = Field("organizational", title="Kind")


class HTTPException(BaseModel):
    status_code: int = Field(..., title="Status Code")
    error_code: str | None = Field("", title="Error Code")
    detail: dict[str, Any] | list[Any] | str | None = Field("", title="Detail")
    errors: dict[str, Any] | list[Any] | str | None = Field("", title="Errors")


class Operator1(RootModel[Literal["in"]]):
    root: Literal["in"] = Field("in", title="Operator")


class InPredicate(BaseModel):
    operator: Literal["in"] = Field("in", title="Operator")
    values: list[str] = Field(..., title="Values")


class LinkMplkRequest(BaseModel):
    login: str = Field(..., title="Login")
    raw_password: str = Field(..., title="Raw Password")


class MessengerLinkRequest(BaseModel):
    messenger_type: str = Field(..., title="Messenger Type")
    id_token: str = Field(..., title="Id Token")


class MessengerResponse(BaseModel):
    id: UUID = Field(..., title="Id")
    messenger_type: str = Field(..., title="Messenger Type")
    messenger_user_id: str = Field(..., title="Messenger User Id")
    linked_at: datetime = Field(..., title="Linked At")


class MessengerUnlinkResponse(BaseModel):
    detail: str = Field(..., title="Detail")


class MfaMethod(StrEnum):
    none = "none"
    email = "email"


class Type1(RootModel[Literal["mplk"]]):
    root: Literal["mplk"] = Field("mplk", title="Type")


class MplkLogin(BaseModel):
    type: Literal["mplk"] = Field("mplk", title="Type")
    login: str = Field(..., title="Login")
    raw_password: str = Field(..., title="Raw Password")


class Kind10(RootModel[Literal["not"]]):
    root: Literal["not"] = Field(..., title="Kind")


class Kind12(RootModel[Literal["or"]]):
    root: Literal["or"] = Field(..., title="Kind")


class OrderApprove(BaseModel):
    id: UUID = Field(..., title="Id")
    approve: bool = Field(..., title="Approve")


class TargetRole(StrEnum):
    student = "student"
    staff = "staff"
    admin = "admin"
    super_admin = "super_admin"
    faculty_admin = "faculty_admin"
    department_admin = "department_admin"


class OrderCreate(BaseModel):
    user_id: UUID | None = Field(None, title="User Id")
    service_id: UUID | None = Field(None, title="Service Id")
    target_role: TargetRole = Field(..., title="Target Role")
    comment: str = Field(..., title="Comment")


class OrderList(BaseModel):
    limit: int = Field(..., title="Limit")
    offset: int = Field(..., title="Offset")
    service_id: UUID | None = Field(None, title="Service Id")


class OrderUpdate(BaseModel):
    id: UUID = Field(..., title="Id")
    user_id: UUID | None = Field(None, title="User Id")
    service_id: UUID | None = Field(None, title="Service Id")
    target_role: TargetRole = Field(..., title="Target Role")
    comment: str = Field(..., title="Comment")


class Type2(RootModel[Literal["password"]]):
    root: Literal["password"] = Field("password", title="Type")


class PasswordLogin(BaseModel):
    type: Literal["password"] = Field("password", title="Type")
    email: str = Field(..., title="Email")
    raw_password: str = Field(..., title="Raw Password")


class PermissionCreate(BaseModel):
    service_id: UUID = Field(..., title="Service Id")
    title: str = Field(..., title="Title")
    verbose_name: str = Field(..., title="Verbose Name")


class PermissionGetByFiltersRequest(BaseModel):
    service_name: str | None = Field(None, title="Service Name")


class PermissionResponse(BaseModel):
    id: UUID = Field(..., title="Id")
    service_id: UUID | None = Field(..., title="Service Id")
    title: str = Field(..., title="Title")
    verbose_name: str = Field(..., title="Verbose Name")


class PermissionSortFieldName(StrEnum):
    id = "id"


class PermissionUpdate(BaseModel):
    id: UUID = Field(..., title="Id")
    service_id: UUID = Field(..., title="Service Id")
    title: str = Field(..., title="Title")
    verbose_name: str = Field(..., title="Verbose Name")


class Kind14(RootModel[Literal["predicate"]]):
    root: Literal["predicate"] = Field(..., title="Kind")


class Operator2(RootModel[Literal["reference"]]):
    root: Literal["reference"] = Field("reference", title="Operator")


class ReferencePredicate(BaseModel):
    operator: Literal["reference"] = Field("reference", title="Operator")
    ids: list[UUID] = Field(..., min_length=1, title="Ids")


class Operator3(RootModel[Literal["regex"]]):
    root: Literal["regex"] = Field("regex", title="Operator")


class RegexPredicate(BaseModel):
    operator: Literal["regex"] = Field("regex", title="Operator")
    value: str = Field(..., title="Value")


class ScopeTemplate(StrEnum):
    unscoped = "unscoped"
    unit_id = "unit_id"
    unit_type_id = "unit_type_id"


class ServiceColorUpdate(BaseModel):
    id: UUID = Field(..., title="Id")
    color: str = Field(..., title="Color")


class ServiceCreate(BaseModel):
    name: str = Field(..., title="Name")
    verbose_name: str | None = Field(None, title="Verbose Name")
    icon: str | None = Field("mdi-briefcase-outline", title="Icon")
    color: str | None = Field("#4B6EB9", title="Color")


class ServiceGetByFiltersRequest(BaseModel):
    service_name: str | None = Field(None, title="Service Name")


class ServiceIconUpdate(BaseModel):
    id: UUID = Field(..., title="Id")
    icon: str = Field(..., title="Icon")


class ServiceResponse(BaseModel):
    id: UUID | None = Field(None, title="Id")
    name: str = Field(..., title="Name")
    verbose_name: str | None = Field(None, title="Verbose Name")
    icon: str | None = Field("mdi-briefcase-outline", title="Icon")
    color: str | None = Field("#4B6EB9", title="Color")


class ServiceRoleGetByFiltersRequest(BaseModel):
    service_name: str | None = Field(None, title="Service Name")


class ServiceRoleSortFieldName(StrEnum):
    id = "id"


class ServiceRolesAssignPermission(BaseModel):
    permission_id: UUID = Field(..., title="Permission Id")
    service_role_id: UUID = Field(..., title="Service Role Id")


class Role(StrEnum):
    student = "student"
    staff = "staff"
    admin = "admin"
    super_admin = "super_admin"
    faculty_admin = "faculty_admin"
    department_admin = "department_admin"


class ServiceRolesCreate(BaseModel):
    service_id: UUID | None = Field(None, title="Service Id")
    role: Role = Field(..., title="Role")
    verbose_name: str | None = Field(None, title="Verbose Name")


class ServiceRolesPermissionDto(BaseModel):
    permission_id: UUID = Field(..., title="Permission Id")
    service_role_id: UUID = Field(..., title="Service Role Id")


class ServiceRolesPermissionsResponse(BaseModel):
    data: list[ServiceRolesPermissionDto] = Field(..., title="Data")


class ServiceRolesResponse(BaseModel):
    id: UUID = Field(..., title="Id")
    service_id: UUID | None = Field(None, title="Service Id")
    role: Role = Field(..., title="Role")
    verbose_name: str | None = Field(None, title="Verbose Name")
    permanent: bool | None = Field(False, title="Permanent")


class ServiceRolesRevokePermission(BaseModel):
    permission_id: UUID = Field(..., title="Permission Id")
    service_role_id: UUID = Field(..., title="Service Role Id")


class ServiceRolesUpdate(BaseModel):
    id: UUID = Field(..., title="Id")
    role: Role = Field(..., title="Role")
    service_id: UUID | None = Field(None, title="Service Id")
    verbose_name: str | None = Field(None, title="Verbose Name")


class ServiceSortFieldName(StrEnum):
    id = "id"


class ServiceUpdate(BaseModel):
    id: UUID = Field(..., title="Id")
    name: str = Field(..., title="Name")
    verbose_name: str | None = Field(None, title="Verbose Name")


class SortOrder(StrEnum):
    ASC = "ASC"
    DESC = "DESC"


class AccountType1(RootModel[Literal["staff"]]):
    root: Literal["staff"] = Field("staff", title="Account Type")


class AccountType2(RootModel[Literal["stud"]]):
    root: Literal["stud"] = Field("stud", title="Account Type")


class Type3(RootModel[Literal["unit"]]):
    root: Literal["unit"] = Field("unit", title="Type")


class UnitScopeItem(BaseModel):
    type: Literal["unit"] = Field("unit", title="Type")
    unit_id: UUID = Field(..., title="Unit Id")


class UnitScopeResponse(BaseModel):
    id: UUID = Field(..., title="Id")
    type: Literal["unit"] = Field("unit", title="Type")
    unit_id: UUID = Field(..., title="Unit Id")


class UnitType(BaseModel):
    id: UUID = Field(..., title="Id")
    title: str = Field(..., title="Title")


class Type5(RootModel[Literal["unit_type"]]):
    root: Literal["unit_type"] = Field("unit_type", title="Type")


class UnitTypeScopeItem(BaseModel):
    type: Literal["unit_type"] = Field("unit_type", title="Type")
    unit_type_id: UUID = Field(..., title="Unit Type Id")


class UnitTypeScopeResponse(BaseModel):
    id: UUID = Field(..., title="Id")
    type: Literal["unit_type"] = Field("unit_type", title="Type")
    unit_type_id: UUID = Field(..., title="Unit Type Id")


class UserAssignService(BaseModel):
    user_id: UUID = Field(..., title="User Id")
    service_id: UUID = Field(..., title="Service Id")


class UserAuthData(BaseModel):
    user_id: UUID = Field(..., title="User Id")
    access_token: str = Field(..., title="Access Token")
    refresh_token: UUID = Field(..., title="Refresh Token")


class UserCreateResponse(BaseModel):
    id: str = Field(..., title="Id")


class UserEmail(BaseModel):
    id: UUID = Field(..., title="Id")
    email: str = Field(..., title="Email")
    is_primary: bool = Field(..., title="Is Primary")
    verified_at: datetime | None = Field(..., title="Verified At")


class UserGetByFiltersRequest(BaseModel):
    email: str | None = Field(None, title="Email")
    service_name: str | None = Field(None, title="Service Name")
    service_role: str | None = Field(None, title="Service Role")
    role: AccountType | list[AccountType] | None = Field(None, title="Role")
    can_manage_services: bool | None = Field(None, title="Can Manage Services")


class UserKind(StrEnum):
    natural = "natural"
    organizational = "organizational"


class UserLogoutRequest(BaseModel):
    refresh_token: UUID = Field(..., title="Refresh Token")


class UserRevokeService(BaseModel):
    user_id: UUID = Field(..., title="User Id")
    service_id: UUID = Field(..., title="Service Id")


class UserServiceRolesCreate(BaseModel):
    service_roles_id: UUID | None = Field(None, title="Service Roles Id")
    user_id: UUID | None = Field(None, title="User Id")
    scope: list[Annotated[UnitScopeItem | UnitTypeScopeItem, Field(discriminator="type")]] | None = Field(
        None, title="Scope"
    )


class UserServiceRolesResponse(BaseModel):
    id: UUID = Field(..., title="Id")
    service_roles_id: UUID | None = Field(None, title="Service Roles Id")
    user_id: UUID | None = Field(None, title="User Id")
    scope: list[Annotated[UnitScopeResponse | UnitTypeScopeResponse, Field(discriminator="type")]] | None = Field(
        [], title="Scope", validate_default=True
    )


class UserServiceRolesUpdate(BaseModel):
    id: UUID = Field(..., title="Id")
    user_id: UUID = Field(..., title="User Id")
    service_roles_id: UUID = Field(..., title="Service Roles Id")
    scope: list[Annotated[UnitScopeItem | UnitTypeScopeItem, Field(discriminator="type")]] | None = Field(
        None, title="Scope"
    )


class UserSex(StrEnum):
    Male = "Male"
    Female = "Female"


class UserSignUp(BaseModel):
    name: str = Field(..., title="Name")
    surname: str = Field(..., title="Surname")
    patronymic: str = Field(..., title="Patronymic")
    email: str = Field(..., title="Email")
    raw_password: str = Field(..., title="Raw Password")


class UserSortFieldName(StrEnum):
    id = "id"
    external_id = "external_id"
    role = "role"
    external_role = "external_role"
    name = "name"
    surname = "surname"
    patronymic = "patronymic"
    email = "email"
    login = "login"
    password = "password"
    last_login = "last_login"
    created_at = "created_at"


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")


class VerificationAuthCode(BaseModel):
    pre_auth_token: str = Field(..., title="Pre Auth Token")
    code: str | None = Field(None, title="Code")


class AuthChallengeResponse(BaseModel):
    pre_auth_token: str = Field(..., title="Pre Auth Token")
    mfa_method: MfaMethod
    mfa_required: bool = Field(..., title="Mfa Required")


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title="Detail")


class PredicateExpression(BaseModel):
    kind: Literal["predicate"] = Field(..., title="Kind")
    field: str = Field(..., title="Field")
    predicate: EqualPredicate | RegexPredicate | InPredicate | ReferencePredicate = Field(
        ..., discriminator="operator", title="Predicate"
    )


class ShortUnit(BaseModel):
    id: UUID = Field(..., title="Id")
    title: str = Field(..., title="Title")
    type: UnitType


class StudentAccount(BaseModel):
    id: UUID = Field(..., title="Id")
    account_type: Literal["stud"] = Field("stud", title="Account Type")
    mplk_user_id: int = Field(..., title="Mplk User Id")
    status: str = Field(..., title="Status")
    course: int = Field(..., title="Course")
    code: str = Field(..., title="Code")
    study_group: str = Field(..., title="Study Group")
    vacation_start: datetime | None = Field(..., title="Vacation Start")
    vacation_end: datetime | None = Field(..., title="Vacation End")
    speciality: str = Field(..., title="Speciality")
    specialization: str = Field(..., title="Specialization")
    degree_length: str = Field(..., title="Degree Length")
    degree_length_standart: str = Field(..., title="Degree Length Standart")
    education_form: str = Field(..., title="Education Form")
    finance: str = Field(..., title="Finance")
    degree_level: str = Field(..., title="Degree Level")
    enter_year: str = Field(..., title="Enter Year")
    pass_expire_date: datetime | None = Field(..., title="Pass Expire Date")
    pass_expired: bool = Field(..., title="Pass Expired")
    last_access: date = Field(..., title="Last Access")
    faculty: ShortUnit


class User(BaseModel):
    id: UUID = Field(..., title="Id")
    kind: UserKind
    mfa_method: MfaMethod
    last_active_account_id: UUID | None = Field(..., title="Last Active Account Id")
    last_login_at: datetime | None = Field(..., title="Last Login At")
    emails: list[UserEmail] = Field(..., title="Emails")
    fullname: str = Field(..., title="Fullname")


class UserGetRolesFromServiceResp(BaseModel):
    roles: list[UserServiceRolesResponse] = Field(..., title="Roles")


class FullOrganizationalUser(BaseModel):
    id: UUID = Field(..., title="Id")
    kind: Literal["organizational"] = Field("organizational", title="Kind")
    mfa_method: MfaMethod
    last_active_account_id: UUID | None = Field(..., title="Last Active Account Id")
    last_login_at: datetime | None = Field(..., title="Last Login At")
    emails: list[UserEmail] = Field(..., title="Emails")
    fullname: str = Field(..., title="Fullname")
    display_name: str = Field(..., title="Display Name")
    units: list[ShortUnit] = Field(..., title="Units")


class OrderResponse(BaseModel):
    id: UUID = Field(..., title="Id")
    user_id: UUID | None = Field(None, title="User Id")
    service_id: UUID | None = Field(None, title="Service Id")
    target_role: TargetRole = Field(..., title="Target Role")
    comment: str = Field(..., title="Comment")
    user: User | None = None


class Position(BaseModel):
    id: UUID = Field(..., title="Id")
    unit: ShortUnit
    post: str = Field(..., title="Post")
    job_type: str = Field(..., title="Job Type")
    wage: float = Field(..., title="Wage")
    category: str = Field(..., title="Category")
    status: str = Field(..., title="Status")
    address: str = Field(..., title="Address")
    room: str = Field(..., title="Room")
    phone_inner: str = Field(..., title="Phone Inner")
    phone_direct: str = Field(..., title="Phone Direct")


class StaffAccount(BaseModel):
    id: UUID = Field(..., title="Id")
    account_type: Literal["staff"] = Field("staff", title="Account Type")
    mplk_user_id: int = Field(..., title="Mplk User Id")
    email_staff: str | None = Field(..., title="Email Staff")
    phone_staff: str | None = Field(..., title="Phone Staff")
    allow_mobphone_in: bool = Field(..., title="Allow Mobphone In")
    allow_mobphone_out: bool = Field(..., title="Allow Mobphone Out")
    positions: list[Position] = Field(..., title="Positions")


class UserAccountsResponse(BaseModel):
    accounts: list[Annotated[StaffAccount | StudentAccount, Field(discriminator="account_type")]] = Field(
        ..., title="Accounts"
    )
    active_account_id: UUID | None = Field(..., title="Active Account Id")


class FullNaturalUser(BaseModel):
    id: UUID = Field(..., title="Id")
    kind: Literal["natural"] = Field("natural", title="Kind")
    mfa_method: MfaMethod
    last_active_account_id: UUID | None = Field(..., title="Last Active Account Id")
    last_login_at: datetime | None = Field(..., title="Last Login At")
    emails: list[UserEmail] = Field(..., title="Emails")
    fullname: str = Field(..., title="Fullname")
    mplk_individual_guid: UUID | None = Field(..., title="Mplk Individual Guid")
    name: str | None = Field(..., title="Name")
    surname: str | None = Field(..., title="Surname")
    patronymic: str | None = Field(..., title="Patronymic")
    sex: UserSex | None
    birthday: date | None = Field(..., title="Birthday")
    phone: str | None = Field(..., title="Phone")
    photo_url: str | None = Field(..., title="Photo Url")
    accounts: list[Annotated[StaffAccount | StudentAccount, Field(discriminator="account_type")]] = Field(
        ..., title="Accounts"
    )


class FullUserEntityModel(RootModel[FullNaturalUser | FullOrganizationalUser]):
    root: FullNaturalUser | FullOrganizationalUser = Field(..., discriminator="kind", title="FullUserEntityModel")


class AllOfExpression(BaseModel):
    kind: Literal["all_of"] = Field(..., title="Kind")
    field: str = Field(..., title="Field")
    item: (
        AndExpression
        | OrExpression
        | NotExpression
        | PredicateExpression
        | FieldExpression
        | AnyOfExpression
        | AllOfExpression
    ) = Field(
        ...,
        discriminator="kind",
        title="RootModel[Annotated[Union[AndExpression, OrExpression, NotExpression, PredicateExpression, FieldExpression, AnyOfExpression, AllOfExpression], FieldInfo(annotation=NoneType, required=True, discriminator='kind')]]",
    )


class AllOfExpression1(BaseModel):
    kind: Literal["all_of"] = Field(..., title="Kind")
    field: str = Field(..., title="Field")
    item: (
        AndExpression1
        | OrExpression1
        | NotExpression1
        | PredicateExpression
        | FieldExpression1
        | AnyOfExpression1
        | AllOfExpression1
    ) = Field(
        ...,
        discriminator="kind",
        title="RootModel[Annotated[Union[AndExpression, OrExpression, NotExpression, PredicateExpression, FieldExpression, AnyOfExpression, AllOfExpression], FieldInfo(annotation=NoneType, required=True, discriminator='kind')]]",
    )


class AndExpression(BaseModel):
    kind: Literal["and"] = Field(..., title="Kind")
    items: list[
        Annotated[
            AndExpression
            | OrExpression
            | NotExpression
            | PredicateExpression
            | FieldExpression
            | AnyOfExpression
            | AllOfExpression,
            Field(discriminator="kind"),
        ]
    ] = Field(..., title="Items")


class AndExpression1(BaseModel):
    kind: Literal["and"] = Field(..., title="Kind")
    items: list[
        Annotated[
            AndExpression1
            | OrExpression1
            | NotExpression1
            | PredicateExpression
            | FieldExpression1
            | AnyOfExpression1
            | AllOfExpression1,
            Field(discriminator="kind"),
        ]
    ] = Field(..., title="Items")


class AnyOfExpression(BaseModel):
    kind: Literal["any_of"] = Field(..., title="Kind")
    field: str = Field(..., title="Field")
    item: (
        AndExpression
        | OrExpression
        | NotExpression
        | PredicateExpression
        | FieldExpression
        | AnyOfExpression
        | AllOfExpression
    ) = Field(
        ...,
        discriminator="kind",
        title="RootModel[Annotated[Union[AndExpression, OrExpression, NotExpression, PredicateExpression, FieldExpression, AnyOfExpression, AllOfExpression], FieldInfo(annotation=NoneType, required=True, discriminator='kind')]]",
    )


class AnyOfExpression1(BaseModel):
    kind: Literal["any_of"] = Field(..., title="Kind")
    field: str = Field(..., title="Field")
    item: (
        AndExpression1
        | OrExpression1
        | NotExpression1
        | PredicateExpression
        | FieldExpression1
        | AnyOfExpression1
        | AllOfExpression1
    ) = Field(
        ...,
        discriminator="kind",
        title="RootModel[Annotated[Union[AndExpression, OrExpression, NotExpression, PredicateExpression, FieldExpression, AnyOfExpression, AllOfExpression], FieldInfo(annotation=NoneType, required=True, discriminator='kind')]]",
    )


class AssignmentRuleCreate(BaseModel):
    title: str = Field(..., title="Title")
    service_role_id: UUID = Field(..., title="Service Role Id")
    expression: (
        AndExpression
        | OrExpression
        | NotExpression
        | PredicateExpression
        | FieldExpression
        | AnyOfExpression
        | AllOfExpression
    ) = Field(..., discriminator="kind", title="Expression")
    enabled: bool | None = Field(True, title="Enabled")
    scope_template: ScopeTemplate | None = "unscoped"


class AssignmentRuleResponse(BaseModel):
    id: UUID = Field(..., title="Id")
    title: str = Field(..., title="Title")
    enabled: bool = Field(..., title="Enabled")
    service_role_id: UUID = Field(..., title="Service Role Id")
    expression: (
        AndExpression1
        | OrExpression1
        | NotExpression1
        | PredicateExpression
        | FieldExpression1
        | AnyOfExpression1
        | AllOfExpression1
    ) = Field(
        ...,
        discriminator="kind",
        title="RootModel[Annotated[Union[AndExpression, OrExpression, NotExpression, PredicateExpression, FieldExpression, AnyOfExpression, AllOfExpression], FieldInfo(annotation=NoneType, required=True, discriminator='kind')]]",
    )
    scope_template: ScopeTemplate


class AssignmentRuleUpdate(BaseModel):
    id: UUID = Field(..., title="Id")
    title: str | None = Field(None, title="Title")
    service_role_id: UUID | None = Field(None, title="Service Role Id")
    expression: (
        AndExpression
        | OrExpression
        | NotExpression
        | PredicateExpression
        | FieldExpression
        | AnyOfExpression
        | AllOfExpression
        | None
    ) = Field(None, title="Expression")
    enabled: bool | None = Field(None, title="Enabled")
    scope_template: ScopeTemplate | None = None


class FieldExpression(BaseModel):
    kind: Literal["field"] = Field(..., title="Kind")
    field: str = Field(..., title="Field")
    item: (
        AndExpression
        | OrExpression
        | NotExpression
        | PredicateExpression
        | FieldExpression
        | AnyOfExpression
        | AllOfExpression
    ) = Field(
        ...,
        discriminator="kind",
        title="RootModel[Annotated[Union[AndExpression, OrExpression, NotExpression, PredicateExpression, FieldExpression, AnyOfExpression, AllOfExpression], FieldInfo(annotation=NoneType, required=True, discriminator='kind')]]",
    )


class FieldExpression1(BaseModel):
    kind: Literal["field"] = Field(..., title="Kind")
    field: str = Field(..., title="Field")
    item: (
        AndExpression1
        | OrExpression1
        | NotExpression1
        | PredicateExpression
        | FieldExpression1
        | AnyOfExpression1
        | AllOfExpression1
    ) = Field(
        ...,
        discriminator="kind",
        title="RootModel[Annotated[Union[AndExpression, OrExpression, NotExpression, PredicateExpression, FieldExpression, AnyOfExpression, AllOfExpression], FieldInfo(annotation=NoneType, required=True, discriminator='kind')]]",
    )


class NotExpression(BaseModel):
    kind: Literal["not"] = Field(..., title="Kind")
    item: (
        AndExpression
        | OrExpression
        | NotExpression
        | PredicateExpression
        | FieldExpression
        | AnyOfExpression
        | AllOfExpression
    ) = Field(
        ...,
        discriminator="kind",
        title="RootModel[Annotated[Union[AndExpression, OrExpression, NotExpression, PredicateExpression, FieldExpression, AnyOfExpression, AllOfExpression], FieldInfo(annotation=NoneType, required=True, discriminator='kind')]]",
    )


class NotExpression1(BaseModel):
    kind: Literal["not"] = Field(..., title="Kind")
    item: (
        AndExpression1
        | OrExpression1
        | NotExpression1
        | PredicateExpression
        | FieldExpression1
        | AnyOfExpression1
        | AllOfExpression1
    ) = Field(
        ...,
        discriminator="kind",
        title="RootModel[Annotated[Union[AndExpression, OrExpression, NotExpression, PredicateExpression, FieldExpression, AnyOfExpression, AllOfExpression], FieldInfo(annotation=NoneType, required=True, discriminator='kind')]]",
    )


class OrExpression(BaseModel):
    kind: Literal["or"] = Field(..., title="Kind")
    items: list[
        Annotated[
            AndExpression
            | OrExpression
            | NotExpression
            | PredicateExpression
            | FieldExpression
            | AnyOfExpression
            | AllOfExpression,
            Field(discriminator="kind"),
        ]
    ] = Field(..., title="Items")


class OrExpression1(BaseModel):
    kind: Literal["or"] = Field(..., title="Kind")
    items: list[
        Annotated[
            AndExpression1
            | OrExpression1
            | NotExpression1
            | PredicateExpression
            | FieldExpression1
            | AnyOfExpression1
            | AllOfExpression1,
            Field(discriminator="kind"),
        ]
    ] = Field(..., title="Items")


class RootModelAnnotatedUnionAndExpressionOrExpressionNotExpressionPredicateExpressionFieldExpressionAnyOfExpressionAllOfExpressionFieldInfoAnnotationNoneTypeRequiredTrueDiscriminatorKindInput(
    RootModel[
        AndExpression
        | OrExpression
        | NotExpression
        | PredicateExpression
        | FieldExpression
        | AnyOfExpression
        | AllOfExpression
    ]
):
    root: (
        AndExpression
        | OrExpression
        | NotExpression
        | PredicateExpression
        | FieldExpression
        | AnyOfExpression
        | AllOfExpression
    ) = Field(
        ...,
        discriminator="kind",
        title="RootModel[Annotated[Union[AndExpression, OrExpression, NotExpression, PredicateExpression, FieldExpression, AnyOfExpression, AllOfExpression], FieldInfo(annotation=NoneType, required=True, discriminator='kind')]]",
    )


class RootModelAnnotatedUnionAndExpressionOrExpressionNotExpressionPredicateExpressionFieldExpressionAnyOfExpressionAllOfExpressionFieldInfoAnnotationNoneTypeRequiredTrueDiscriminatorKindOutput(
    RootModel[
        AndExpression1
        | OrExpression1
        | NotExpression1
        | PredicateExpression
        | FieldExpression1
        | AnyOfExpression1
        | AllOfExpression1
    ]
):
    root: (
        AndExpression1
        | OrExpression1
        | NotExpression1
        | PredicateExpression
        | FieldExpression1
        | AnyOfExpression1
        | AllOfExpression1
    ) = Field(
        ...,
        discriminator="kind",
        title="RootModel[Annotated[Union[AndExpression, OrExpression, NotExpression, PredicateExpression, FieldExpression, AnyOfExpression, AllOfExpression], FieldInfo(annotation=NoneType, required=True, discriminator='kind')]]",
    )


AllOfExpression.model_rebuild()
AllOfExpression1.model_rebuild()
AndExpression.model_rebuild()
AndExpression1.model_rebuild()
AnyOfExpression.model_rebuild()
AnyOfExpression1.model_rebuild()
AssignmentRuleCreate.model_rebuild()
AssignmentRuleResponse.model_rebuild()
AssignmentRuleUpdate.model_rebuild()
FieldExpression.model_rebuild()
FieldExpression1.model_rebuild()
NotExpression.model_rebuild()
NotExpression1.model_rebuild()
OrExpression.model_rebuild()
OrExpression1.model_rebuild()
