"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GetPayloadRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_FIELD_NUMBER: _builtins.int
    token: _builtins.str
    def __init__(
        self,
        *,
        token: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetPayloadRequest: _TypeAlias = GetPayloadRequest  # noqa: Y015

@_typing.final
class GetPayloadResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    ROLE_FIELD_NUMBER: _builtins.int
    EXPIRES_AT_FIELD_NUMBER: _builtins.int
    SERVICE_NAME_FIELD_NUMBER: _builtins.int
    PERMISSIONS_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    role: _builtins.str
    expires_at: _builtins.str
    """ISO 8601 format"""
    service_name: _builtins.str
    @_builtins.property
    def permissions(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        role: _builtins.str = ...,
        expires_at: _builtins.str = ...,
        service_name: _builtins.str = ...,
        permissions: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["expires_at", b"expires_at", "permissions", b"permissions", "role", b"role", "service_name", b"service_name", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetPayloadResponse: _TypeAlias = GetPayloadResponse  # noqa: Y015

@_typing.final
class GetUserRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_FIELD_NUMBER: _builtins.int
    token: _builtins.str
    def __init__(
        self,
        *,
        token: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetUserRequest: _TypeAlias = GetUserRequest  # noqa: Y015

@_typing.final
class GetUserResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    EXTERNAL_ID_FIELD_NUMBER: _builtins.int
    ROLE_FIELD_NUMBER: _builtins.int
    EXTERNAL_ROLE_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    SURNAME_FIELD_NUMBER: _builtins.int
    PATRONYMIC_FIELD_NUMBER: _builtins.int
    EMAIL_FIELD_NUMBER: _builtins.int
    FACULTY_FIELD_NUMBER: _builtins.int
    LOGIN_FIELD_NUMBER: _builtins.int
    LAST_LOGIN_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    SEX_FIELD_NUMBER: _builtins.int
    STUDY_STATUS_FIELD_NUMBER: _builtins.int
    DEGREE_LEVEL_FIELD_NUMBER: _builtins.int
    STUDY_GROUP_FIELD_NUMBER: _builtins.int
    SPECIALIZATION_FIELD_NUMBER: _builtins.int
    FINANCE_FIELD_NUMBER: _builtins.int
    FORM_FIELD_NUMBER: _builtins.int
    ENTER_YEAR_FIELD_NUMBER: _builtins.int
    COURSE_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    DEPARTMENT_CODE_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    external_id: _builtins.str
    role: _builtins.str
    external_role: _builtins.str
    name: _builtins.str
    surname: _builtins.str
    patronymic: _builtins.str
    email: _builtins.str
    faculty: _builtins.str
    login: _builtins.str
    last_login: _builtins.str
    created_at: _builtins.str
    sex: _builtins.str
    study_status: _builtins.str
    degree_level: _builtins.str
    study_group: _builtins.str
    specialization: _builtins.str
    finance: _builtins.str
    form: _builtins.str
    enter_year: _builtins.str
    course: _builtins.str
    type: _builtins.str
    department_code: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        external_id: _builtins.str = ...,
        role: _builtins.str = ...,
        external_role: _builtins.str = ...,
        name: _builtins.str = ...,
        surname: _builtins.str = ...,
        patronymic: _builtins.str = ...,
        email: _builtins.str = ...,
        faculty: _builtins.str = ...,
        login: _builtins.str = ...,
        last_login: _builtins.str = ...,
        created_at: _builtins.str = ...,
        sex: _builtins.str = ...,
        study_status: _builtins.str = ...,
        degree_level: _builtins.str = ...,
        study_group: _builtins.str = ...,
        specialization: _builtins.str = ...,
        finance: _builtins.str = ...,
        form: _builtins.str = ...,
        enter_year: _builtins.str = ...,
        course: _builtins.str = ...,
        type: _builtins.str = ...,
        department_code: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["course", b"course", "created_at", b"created_at", "degree_level", b"degree_level", "department_code", b"department_code", "email", b"email", "enter_year", b"enter_year", "external_id", b"external_id", "external_role", b"external_role", "faculty", b"faculty", "finance", b"finance", "form", b"form", "id", b"id", "last_login", b"last_login", "login", b"login", "name", b"name", "patronymic", b"patronymic", "role", b"role", "sex", b"sex", "specialization", b"specialization", "study_group", b"study_group", "study_status", b"study_status", "surname", b"surname", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetUserResponse: _TypeAlias = GetUserResponse  # noqa: Y015
