"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CreatePermission(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TITLE_FIELD_NUMBER: _builtins.int
    VERBOSE_NAME_FIELD_NUMBER: _builtins.int
    title: _builtins.str
    verbose_name: _builtins.str
    def __init__(
        self,
        *,
        title: _builtins.str = ...,
        verbose_name: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["title", b"title", "verbose_name", b"verbose_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreatePermission: _TypeAlias = CreatePermission  # noqa: Y015

@_typing.final
class Permission(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    VERBOSE_NAME_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    title: _builtins.str
    verbose_name: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        title: _builtins.str = ...,
        verbose_name: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "title", b"title", "verbose_name", b"verbose_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Permission: _TypeAlias = Permission  # noqa: Y015

@_typing.final
class GetPermissionsByServiceRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SERVICE_NAME_FIELD_NUMBER: _builtins.int
    service_name: _builtins.str
    def __init__(
        self,
        *,
        service_name: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["service_name", b"service_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetPermissionsByServiceRequest: _TypeAlias = GetPermissionsByServiceRequest  # noqa: Y015

@_typing.final
class GetPermissionsByServiceResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PERMISSIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def permissions(self) -> _containers.RepeatedCompositeFieldContainer[Global___Permission]: ...
    def __init__(
        self,
        *,
        permissions: _abc.Iterable[Global___Permission] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["permissions", b"permissions"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetPermissionsByServiceResponse: _TypeAlias = GetPermissionsByServiceResponse  # noqa: Y015

@_typing.final
class CreateServicePermissionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SERVICE_NAME_FIELD_NUMBER: _builtins.int
    PERMISSION_FIELD_NUMBER: _builtins.int
    service_name: _builtins.str
    @_builtins.property
    def permission(self) -> Global___CreatePermission: ...
    def __init__(
        self,
        *,
        service_name: _builtins.str = ...,
        permission: Global___CreatePermission | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["permission", b"permission"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["permission", b"permission", "service_name", b"service_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateServicePermissionRequest: _TypeAlias = CreateServicePermissionRequest  # noqa: Y015

@_typing.final
class CreateServicePermissionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PERMISSION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def permission(self) -> Global___Permission: ...
    def __init__(
        self,
        *,
        permission: Global___Permission | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["permission", b"permission"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["permission", b"permission"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateServicePermissionResponse: _TypeAlias = CreateServicePermissionResponse  # noqa: Y015

@_typing.final
class UpdateServicePermissionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SERVICE_NAME_FIELD_NUMBER: _builtins.int
    PERMISSION_FIELD_NUMBER: _builtins.int
    service_name: _builtins.str
    @_builtins.property
    def permission(self) -> Global___Permission: ...
    def __init__(
        self,
        *,
        service_name: _builtins.str = ...,
        permission: Global___Permission | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["permission", b"permission"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["permission", b"permission", "service_name", b"service_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateServicePermissionRequest: _TypeAlias = UpdateServicePermissionRequest  # noqa: Y015

@_typing.final
class UpdateServicePermissionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateServicePermissionResponse: _TypeAlias = UpdateServicePermissionResponse  # noqa: Y015

@_typing.final
class DeleteServicePermissionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteServicePermissionRequest: _TypeAlias = DeleteServicePermissionRequest  # noqa: Y015

@_typing.final
class DeleteServicePermissionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteServicePermissionResponse: _TypeAlias = DeleteServicePermissionResponse  # noqa: Y015
